### ISSUE TITLE
Test out HTTP 2 support from libcurl

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/mamba#123]
libcurl can do some stuff for HTTP/2 and we should enable it. This is a reminder :)

**Comment by wolfv** [comment]
I tested it and it didn't have much of an impact on the anaconda.org repos. I think they'd need to activate HTTP/2

**Comment by dhirschfeld** [comment]
Just wondering if it might be useful for `quetz` if the server there is HTTP/2?

I've been thinking of enabling HTTP/2 for our internal repo server but never got around to it. Now I'm planning to move to `quetz`! 😃
