### ISSUE TITLE
Implement CTRL+C and rollback consistently

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/mamba#129]
CTRL+C during download doesn't work right now ... we need to figure out how to handle this correctly.

**Comment by wolfv** [comment]
We have a mechanism now in PR #125 that catches the CTRL+C signal and set's a global boolean (attached to Context) which can / should be used to break out of loops.

**Comment by wolfv** [comment]
Regarding rollback:

We need to implement a RAII transaction context object which channels the filesystem operations and records them at the same time. With the record, we'll be easily able to revert the changes that have been made.

**Comment by wolfv** [comment]
https://thomastrapp.com/blog/signal-handler-for-multithreaded-c++/

This seems relevant

**Comment by JohanMabille** [comment]
Notice that sigwait is not available on Windows, therefore we would need two different implementations.
