### ISSUE TITLE
Keyboard interrupt has not effect

### ISSUE THREAD

**Issue by johanneskoester** [TheSnakePit/mamba#210]
When running an installation, hitting Ctrl-C does not have any effect. Seems like the event is not handled. It should however lead to aborting the installation, ideally even rolling it back.

**Comment by johanneskoester** [comment]
Correction: it has an effect, but very late, and not already while downloading the packages.

**Comment by wolfv** [comment]
can you specify which OS? we have some signal handling for CTRL+C but we might need to hook it up, and indeed, rolling back transactions isn't implemented on the C++ side yet.

**Comment by mkcor** [comment]
I ran into the same impression: I tried Ctrl-C to no avail, then I frantically pressed Ctrl-D, Ctrl-Z, Ctrl-C, Ctrl-D, Ctrl-Z... and something worked.

**Comment by wolfv** [comment]
Mac or Linux? :)

**Comment by mkcor** [comment]
Oh, Debian GNU/Linux! :)

**Comment by wolfv** [comment]
I am merging this into #129
