### ISSUE TITLE
Mamba doesn't support private anaconda channels through anaconda login

### ISSUE THREAD

**Issue by hmaarrfk** [TheSnakePit/mamba#230]
It seems mamba has trouble finding private packages of mine.

```
>mamba --version
conda 4.8.3
```

**Comment by wolfv** [comment]
I am not sure what you mean with private packages: are those local packages e.g. in your conda-bld folder or are they at some internet location?
Can you give us some details about your channel configuration? Are you using a private channel on Anaconda.org or do you have a channel with HTTP authentication set up?

Your issue lacks a lot of detail.

**Comment by wolfv** [comment]
But to answer your question -- mamba should support all channels that conda supports, but we haven't tested private channels as extensively yet.

**Comment by hmaarrfk** [comment]
Sorry for not providing this information.

I have apackage on my paid anaconda anacomda account that has a few packages marked as private.

To get access to them, I either have to login, with the command `anaconda login` or use a token with the correct permissions enabled.

In my case, I'm using `anaconda login`. 

Mamba seems to only see the publicly shared packages on the channel, not the private ones.

Thanks for following up

**Comment by wolfv** [comment]
hey. I think the Token approach would work.
I have filled the contact form on Anaconda.org in order to get some private packages but they have not responded. I'd be happy to test out the integration .. maybe you can poke them?

**Comment by hmaarrfk** [comment]
>  contact form on Anaconda.org in order to get some private packages

Ah so you don't have a paid account (why would you) so you can't test out the use case that I am referring to.

I can confirm that adding the channel with a token seems to work around the login issue.

Maybe it is because `anaconda login` works only in the base environment, and doesn't carry well to mamba install in other environments.

**Comment by wolfv** [comment]
Okay, I dug a little deeper, and if I understand you correctly, you use `anaconda login` as a seperate command, right?

When running `anaconda login`, some files get created in ` ~/.continuum/anaconda-client/tokens`. I am not sure why our current implementation wouldn't pick these tokens up as we're using the same functions that conda uses for getting the `Channel` url with credentials... need to dig a little deeper :)

Other good news are that I have some private packages now, so I can also test this.

**Comment by hmaarrfk** [comment]
You are right, I have a folder `/home/mark/.continuum/anaconda-client/tokens` that has a token to `https%3A%2F%2Fapi.anaconda.org.token` that looks like an anaconda token.

Thanks for digging

**Comment by s22chan** [comment]
That's odd, because the last time I used mamba (Jul 2019) it did support the `anaconda login` saved tokens to access private channels

**Comment by s22chan** [comment]
It seems to have started with `mamba =0.2.0` with the parallel repodata fetching.

**Comment by wolfv** [comment]
makes sense. yeah we need to look into that. I was assuming that using the URL with credentials would apply all the magic, but apparently it does not for this way of supplying tokens.
