### ISSUE TITLE
Rewrite Query

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/mamba#281]
We have a pretty nice query functionality now, but some refactoring is needed.

The idea is to implement a QueryResult class that looks something like this:

```
QueryResult
{
QueryType = {DEPENDS, WHONEEDS, SEARCH}

// These two should change the appearance of the table
groupby() // group by one of the fields, for example channel
sort() // select how to sort, for now by version (upward, downward?)
// so maybe they should be params to the table function

table(ostream) // print a table view
tree(ostream) // print a tree to ostream, only for depends and whoneeds
json(ostream) // get a JSON representation of the result

std::vector<Solvable*> pkgs; ?
}
```

**Comment by wolfv** [comment]
I just realized that since we're sorting by EVR right now, there is a bug when searching with the `*` operator. We need to have a group-by first, then sort.

E.g. `mamba repoquery search xtensor*` returns a mixed list of xtensor-packages:

```
 xtensor        0.7.0   0                          conda-forge/linux-64
 xtensor-blas   0.6.1   blas_openblas_0            conda-forge/linux-64
 xtensor-python 0.6.1   0                          conda-forge/linux-64
 xtensor-blas   0.6.0   blas_openblas_0            conda-forge/linux-64
 xtensor-python 0.6.0   0                          conda-forge/linux-64
 xtensor        0.6.0   0                          conda-forge/linux-64
 xtensor-python 0.5.0   0                          conda-forge/linux-64
 xtensor-blas   0.5.0   blas_openblas_0            conda-forge/linux-64
```

**Comment by xhochy** [comment]
It would also be nice to have the results of `Query` as Python objects, this would be useful in `conda-smithy` where we check the `conda-forge` channel for the latest release of `conda-smithy`.

**Comment by JohanMabille** [comment]
The Query has been rewritten in #306.

The python bindings are still rudimentary. @xhochy Which part of the QueryResult do you need? Is the list of packages enough or do you need the tree view?

**Comment by wolfv** [comment]
I think for this specific use case conda-forge is now using the anaconda API (which totally makes sense). 
I think for mamba & Python, it should be (at least) possible to send a query to mamba, then retrieve the results as JSON / or automagically parsed JSON in Python.

**Comment by xhochy** [comment]
I'm mostly interested for the list of packages with version information. I'm now also using mamba for the package cleanup in https://github.com/apache/arrow/pull/7305/files

Here I could also have used the Anaconda API but I prefer to keep these scripts independent from that one as I plan to use it also on other hosts.

**Comment by wolfv** [comment]
@JohanMabille I guess we can close this, right?

**Comment by JohanMabille** [comment]
We still need to expose the PackageInfo class to Python (and the list of package stored in query result).

**Comment by JohanMabille** [comment]
Let's track this in a dedicated issue
