### ISSUE TITLE
Add option to ignore installed packages in repoquery

### ISSUE THREAD

**Issue by xhochy** [TheSnakePit/mamba#304]
Currently the installed channel is always included. There is an `--installed` flag in the code https://github.com/QuantStack/mamba/blob/603ae3cfdb615e65b2a53ed551370368d2864346/mamba/mamba.py#L716-L720 but it doesn't seem to be used.

Should we add a flag `--no-installed` or should we use the currently unused flag?

**Comment by wolfv** [comment]
it's not entirely true - for repoquery search the installed flag is used. if added, it will limit the search to the installed packages.
On the inverse, we _do_ have support for repoquery depends to print the dependencies of packages in a channel. This is actually super useful but not exposed...

I just added a flag `-a,--all-channels` to do that (need to open the PR). What do you think?

Basically I was thinking:

repodata search: default search all channels from condarc
repodata depends: default search only installed packages
repodata whoneeds: default search only installed packages

and then `--installed` and `--all-channels` to toggle the behavior. 

But if you have a better suggestion I am all ears! I am not super convinced of the CLI argument names here.

**Comment by wolfv** [comment]
I have added these flags now:

```
mamba repoquery search "ipython=7" -p osx-64 --override-channels -c conda-forge --no-installed
```
