### ISSUE TITLE
Add option for platform in repoquery

### ISSUE THREAD

**Issue by xhochy** [TheSnakePit/mamba#305]
Currently `repoquery` is always searching the current platform/subdir. It would also be useful to have an option to search in an alternative platform.

**Comment by wolfv** [comment]
yes that would be great! :) Although the `CONDA_SUBDIR` trick does seem to work.

**Comment by wolfv** [comment]
(for others: `CONDA_SUBDIR=win-64 mamba repoquery search xtensor` searches teh win-64 subdir)
