### ISSUE TITLE
mamba trying to install package build for python 2.7 in an environment with python 3.6

### ISSUE THREAD

**Issue by arunvv90** [TheSnakePit/mamba#340]
I have created a conda enviornment with this comment
 mamba create -c conda-forge -c bioconda -n snakemake snakemake python==3.6
Then I tried to install multiqc package
mamba install multiqc
error message was
encountered problems while solving.
Problem: package multiqc-0.4-py27_0 requires python 2.7*, but none of the providers can be installed
same thing happened with 
mamba install quast==5.0.2
encountered problems while solving.
Problem: package quast-5.0.2-py27pl526ha92aebf_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
I can see from the package list that python 3 builds are available
Thanking you in advance

**Comment by wolfv** [comment]
what's your OS?
does this work with conda?

it's likely an issue with conflicting metadata. if you want to debug it, run mamba with `-vvv` (it will print a lot but at the top you might find some information).

**Comment by arunvv90** [comment]
Hi,
my os is ubuntu 16. I have a working conda environment created with conda
with everything installed. Problem happens in the new environment created
with mamba. I have created another new environment with mamba with python
3.6.7 as default and it has installed multiqc without any problem. I have
the same python version in my old environment created with conda. It
appears that the problem is with the python version of the environment.
Ideally, it should not be a problem and mamba should take care of that.
* Arun Venugopalan*
Ph.D Scholar
Infectious Diseases, Basic Science Dept.
College of Veterinary Medicine
Mississippi State University*,* USA

**Comment by wolfv** [comment]
The issue is that you specified `python` with `==` which is a tight spec for `python==3.6.0`

Use `python=3.6` or `python==3.6.*` and it works.
