### ISSUE TITLE
--quiet is too quiet

### ISSUE THREAD

**Issue by analog-cbarber** [TheSnakePit/mamba#345]
`conda install --quiet` turns off the progress bar but still shows the packages to be installed:

```bash
$ conda install --quiet -n foo deprecation --yes
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/cbarber/miniconda3/envs/foo

  added / updated specs:
    - deprecation


The following NEW packages will be INSTALLED:

  deprecation        conda-forge/noarch::deprecation-2.1.0-pyh9f0ad1d_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

`mamba install --quiet` hides the package information:

```bash
$  mamba install --quiet deprecation -n foo --yes
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

In automated CI builds we often want to turn of the progress bar to avoid useless log spew but still want to see what packages it is installing.

**Comment by wolfv** [comment]
We do something special when the `CI=1` environment variable is set. In that case, we don't print progress bars and only show some simple textual information that will help debugging issues. 
I think quiet should be quiet, and maybe there should be something in between?

**Comment by wolfv** [comment]
https://github.com/TheSnakePit/mamba/blob/c3840980509e025d92f830d417cbdc502bd9a497/src/context.cpp#L53 that's the magic line :)

**Comment by analog-cbarber** [comment]
Good to know about the CI trick. Thanks!

But if mamba is supposed to be a drop in replacement for conda, I would think that it's behavior should be similar unless there is a good reason for it not to be, even if conda did not necessarily make the same choice you would have made. I shouldn't have to customize my command line for trivial stuff like this when switching between the two.

One possibility would be to allow --quiet to be specified multiple times, so you could just write: `--quiet --quiet` or `-qq` to get the current behavior.

**Comment by wolfv** [comment]
This has changed now to be more similar to conda's behavior.
