### ISSUE TITLE
centos 7 support for statically linked micromamba

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/mamba#350]
I am not sure if this is feasible, and wether we need to use C++14 for this? 

@JohanMabille / @SylvainCorlay do you know?

It could be a good baseline

**Comment by JohanMabille** [comment]
Centos 7 defualt compiler is gcc 4.8.5, which does not support C++14. So if you want to support it, you need to install another version of the compiler (because mamba is C++14).

**Comment by SylvainCorlay** [comment]
The xeus-python wheel is built on CentOS 6. This should be fine.

**Comment by wolfv** [comment]
Actually we're using C++ 17 in mamba right now. Although we could drop that if it's really required.

**Comment by wolfv** [comment]
And I don't think we need the C++17 ABI as we don't use std::filesystem

**Comment by SylvainCorlay** [comment]
I don't think it is very reasonable to require C++17.

**Comment by wolfv** [comment]
we were using C++14 in 2017, now it's 2020 and we should use C++17. At least the language support seems good enough. standard library is a bigger problem with the old OS X requirement.

**Comment by SylvainCorlay** [comment]
I agree, although it is not so much about the date as much as it is about compiler support...

**Comment by xhochy** [comment]
The manylinux2014 docker image should have a C++17 supporting compiler on CentOS7, so this might be worth a try.

**Comment by SylvainCorlay** [comment]
I don't think it should be too much of an issue on 2010 either though.

**Comment by wolfv** [comment]
@jjhelmus left a really nice comment on the feedstock (https://github.com/conda-forge/micromamba-feedstock/issues/4)
What do you all think about using `-static-libstdc++` and `-static-libgcc`? It sounds like it would solve all problems (probably at the cost of an increased binary size).

Or should we rather try to link with an old-enough libgcc / libstdc++?
Also, I am not sure if we could setup the compiler infrastructure on conda-forge in a way that it would (dynamically) link against the old system libc++ / libgcc?
If we wanted that we probably would need to use our own container / manylinux... while I _like_ to have the binaries on conda-forge and taking them straight from there.

**Comment by wolfv** [comment]
fixed with #377
