### ISSUE TITLE
Support for PEP 440 style version strings

### ISSUE THREAD

**Issue by jakirkham** [TheSnakePit/mamba#354]
It would be useful to have support for PEP 440 version strings with mamba. In particular PEP 440 has a provision for adding a `+`, which implies anything after a `+` is ignored. This is useful when encoding version control style strings (as noted in the PEP) to identify how a particular build was created. It also used by tools like [setuptools_scm]( https://github.com/pypa/setuptools_scm#default-versioning-scheme ), [versioneer]( https://github.com/warner/python-versioneer ), and possibly others.

**Comment by wolfv** [comment]
Can you give some more illustrative examples as well as compare to the conda matchspec?
Also, how would you expect this to work? We do have a pretty tight spec for the versions from conda, right?
And conda / mamba also ignore everything that's matched following a `*` so if you have packages 

xyz.dev0
xyz.master0
...

you can do `mamba install xyz.*` to install either, or `mamba install xyz.dev*` to install the dev version (at least I am imagining that this woudl work :)

Changing the versionspec would be somtehing that we'd need to do in tandem with conda itself. 

Or are you going for something else here?

**Comment by wolfv** [comment]
@jakirkham ping?

**Comment by jakirkham** [comment]
@trxcllnt, could you please share a simple example of the problem you were running into? 🙂

**Comment by trxcllnt** [comment]
`mamba install ucx-py=0.15*` but the version numbers look like this: `ucx-py==0.15.0a200630+g13ff111`

**Comment by jakirkham** [comment]
How did you specify the channels to `mamba`?

**Comment by wolfv** [comment]
I guess you were using `-c rapidsai-nightly` (I'd appreciate better bug reports ;)

So the problem seems to be in the handling of strings that follow right after the version number. Indeed the selectors posted above don't appear to work as expected with mamba. I will have a look -- this will probably need some changes in libsolv.

**Comment by jakirkham** [comment]
Thanks Wolf! 😄

**Comment by trxcllnt** [comment]
I install all the dependencies by creating the environment from a YAML file, but either way seems to trigger the bug so it didn't seem relevant.

**Comment by dhirschfeld** [comment]
`ucx-py==0.15.0a200630+g13ff111` is a pretty unusual version number.

I *think* it's valid because there's not limit on how many alpha releases you can have (AFAIK) but that implies that it's the 200,630th alpha release of `0.15`

**Comment by dhirschfeld** [comment]
```python
In [31]: import re
    ...: from packaging.version import VERSION_PATTERN

In [32]: regex = re.compile(VERSION_PATTERN, re.VERBOSE|re.IGNORECASE)

In [33]: regex.match('0.15.0a200630+g13ff111').groupdict()
Out[33]: 
{'epoch': None,
 'release': '0.15.0',
 'pre': 'a200630',
 'pre_l': 'a',
 'pre_n': '200630',
 'post': None,
 'post_n1': None,
 'post_l': None,
 'post_n2': None,
 'dev': None,
 'dev_l': None,
 'dev_n': None,
 'local': 'g13ff111'}
```

**Comment by trxcllnt** [comment]
My guess is `200630` is some kind of timestamp

**Comment by dhirschfeld** [comment]
> My guess is 200630 is some kind of timestamp

I'd call that a slight abuse of the version syntax - reinterpreting the pre-release version to inject timestamp information. 

I don't have a big problem with that though. Not being able to easily query the time of build is one of my personal bug-bears - I think the (human-readable) build timestamp should be shown by default, or at least have a `--show-timestamps` option to allow it.

**Comment by jakirkham** [comment]
We can debate the intended use of this feature. However [the PEP]( https://www.python.org/dev/peps/pep-0440/#pre-releases ) outlines this as supported:

> ```
> X.YaN   # Alpha release
> ```

That said, I'm not sure I follow how this is related to the original question about the behavior of `mamba install ucx-py=0.15*`.

**Comment by dhirschfeld** [comment]
> I'm not sure I follow how this is related to the original question

Only that, whilst an unusual usage of the alpha-release version number it *is* allowed by the PEP so needs to be supported.

Anything after the `+` (the local-identifier) can be ignored but other than that the ordering in the PEP should be respected.
```python
In [57]: from packaging.version import Version

In [58]: Version('0.15.0') > Version('0.15.0b0') > Version('0.15.00a200631') > Version('0.15.0a200630+g13ff111') > Version('0.15.0.dev0')
Out[58]: True
```

I'm not sure if ordering is the problem but in case it helps, the `packaging.Version` class implements that using tuple comparison with a custom key:
https://github.com/pypa/packaging/blob/a0b41c21d09150f18232a641a7b6b86edea6f607/packaging/version.py#L488

**Comment by wolfv** [comment]
I have the fix for libsolv here: https://github.com/openSUSE/libsolv/pull/392

Indeed the ordering semantics might be another can of worms but I think that's implemented correctly :)
We should add some tests though

**Comment by wolfv** [comment]
Fixed in libsolv and I will release a patched version of libsolv to conda-forge later today.

**Comment by jakirkham** [comment]
Awesome! Thanks Wolf 😄
