### ISSUE TITLE
Minimamba .sh installer

### ISSUE THREAD

**Issue by EricAlcaide** [TheSnakePit/mamba#359]

**Comment by EricAlcaide** [comment]
Where is the installer for the recent versions?

**Comment by wolfv** [comment]
Hi @EricAlcaide we're working on "micromamba" -- micromamba will be fully statically linked and able to create new environments from scratch.
With micromamba, you'll be able to create environments for mamba, or everything else: https://gist.github.com/wolfv/fe1ea521979973ab1d016d95a589dcde

Currently there is one breaking issue (https://github.com/TheSnakePit/mamba/issues/358) but once that's closed, micromamba should be usable on all Linux architectures as well as OS X. 
We're also working hard to get it to run on Windows, which will hopefully be done by the end of next week.

**Comment by EricAlcaide** [comment]
Many thanks! Looking forward to it!

**Comment by wolfv** [comment]
We've added some instructions to the README now.
