### ISSUE TITLE
[Feature] mamba.api?

### ISSUE THREAD

**Issue by alanhdu** [TheSnakePit/mamba#365]
`conda` provides a [Python API](https://docs.conda.io/projects/conda/en/latest/api/) to some of its internals, with "very long-term stability". This is useful for creating your own wrappers around conda environments (for instance, in our use-case we want to manage a "run" environment that is a subset of our overall "dev" environment), which we can do by hooking into `conda.api.Solver`.

Would there be any interest in providing a similar API for `mamba`? We'd also be alright with using subprocesses if the `mamba` CLI was considered "relatively stable" (e.g. by doing something similar to `conda-lock` to generate lockfiles).

**Comment by wolfv** [comment]
Hi @alanhdu thanks for asking.
We do have an internal API that can be used quite easily: https://gist.github.com/wolfv/cd12bd4a448c77ff02368e97ffdf495a

This is already used in the conda-forge bots and in some other places. I am not sure that the above example will work right now (as there might have been some changes) but you can always look at `mamba.py` to compare.

However, I won't guarantee super longterm stability as of now as we're still in an early stage.

Let me know how this goes!
