### ISSUE TITLE
conda cannot find mamba environment

### ISSUE THREAD

**Issue by feldman4** [TheSnakePit/mamba#372]
```
conda activate df
conda install -c conda-forge mamba
mamba create -c conda-forge -c bioconda -n mamba-test snakemake
conda activate snakemake
```

Installation goes OK but last line fails with `Could not find conda environment: mamba-test`. `mamba info --envs` includes the new environment. `conda info --envs` does not.

**Comment by wolfv** [comment]
yes, mamba _only_ works when installed in the root environment. I will have to make that clearer in the README.
