### ISSUE TITLE
Implement pinning and freezing in a better way

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/mamba#376]
We can use `SOLVER_LOCK` to implement freezing and pinning quite nicely.

In `conda env update` they first try to solve the environment with "freeze installed" -- which we don't do right now. 
If we implement a better interface for these tasks this would be easy to do as well.

x-ref #360

**Comment by dhirschfeld** [comment]
Possibly related? https://github.com/TheSnakePit/mamba/issues/328#issuecomment-641767389
