### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Lesdormis** [TheSnakePit/mamba#411]
Hi, mamba developers,

I have a problem with trying to install the mamba in my Mac conda environment, but it fails for unknown reasons.
The code I tried to install:
$ conda install -c conda-forge mamba
 Then it said,

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

I was wondering do you know how to solve it?

Thanks!

**Comment by wolfv** [comment]
Hi @Lesdormis you should always install mamba in your base environment.

If you have trouble installing mamba, then you probably have some incompatible packages in your base environment.
I would suggest to create a new miniconda installation and remember to often create new environments, and have only very minimal amount of packages in the base environment (e.g. python, conda and mamba in the base environment, everything else in new envs).
