### ISSUE TITLE
`mamba env` falls back to `conda-env`

### ISSUE THREAD

**Issue by fcollonval** [TheSnakePit/mamba#414]
`mamba env` subcommand is falling back to `conda-env` without displaying any warning.

```
(jconda) fcollonval@:~/jupyter_conda/labextension$ mamba env -h
usage: conda-env [-h] {create,export,list,remove,update,config} ...

positional arguments:
  {create,export,list,remove,update,config}
    create              Create an environment based on an environment file
    export              Export a given environment
    list                List the Conda environments
    remove              Remove an environment
    update              Update the current environment based on environment
                        file
    config              Configure a conda environment

optional arguments:
  -h, --help            Show this help message and exit.

conda commands available from other packages:
  env
```

This is inconsistent with other not-supported commands:

```
(jconda) fcollonval@:~/jupyter_conda/labextension$ mamba config --show --json
Currently, only install, create, list, search, run, info and clean are supported through mamba.
```

**Comment by NegatioN** [comment]
I'm pretty sure it solves the dependencies in `mamba` but then does the downloads and installation in `conda`. This seems to not be solved in the core of `mamba` yet, but contributed as a patch: https://medium.com/@wolfv/mamba-development-news-29e32aaa8d6c

Anecdotaly i have a yml file that installs in 4m44s using `conda`, and 4m4s with `mamba`

Having full speed here would really be a huge win for us :slightly_smiling_face:

**Comment by fcollonval** [comment]
Thank you for the pointer @NegatioN 

I guess the command line is faster because the parsing of the requirement file is slow.
