### ISSUE TITLE
Add option to supress logo printing fot mamba run

### ISSUE THREAD

**Issue by Aroksak** [TheSnakePit/mamba#439]
Mamba logo is cool and beautiful, no questions, but I want to use mamba run in a pipeline where I catch stdout and log it and redirect it further and Mamba logo is messing up everything.
I think it would be good to have an option like --silent or something, to disable logo printing in mamba run calls, I think changing stdout is often undesirable in many applications.

**Comment by wolfv** [comment]
yep. PR more than welcome! :)

**Comment by benjamb** [comment]
This looks to have been addressed by https://github.com/TheSnakePit/mamba/pull/444.
