### ISSUE TITLE
Running `shell init` doesn't set `$MAMBA_ROOT_PREFIX` for micromamba

### ISSUE THREAD

**Issue by marimeireles** [TheSnakePit/mamba#457]
I used the following command to initialize my shell:

`./micromamba shell init -s zsh -p ~/micromamba `

And then I tried to create a new environment with the following:

`micromamba create ~/micromamba/mari`

But this didn't work. I got the following error message:

```
No active target prefix.

Run $ micromamba activate <PATH_TO_MY_ENV>
to activate an environment.

```

In my understanding, I already set a path to my `env`, that's what the shell script was supposed to be doing, right?

The only thing that worked for me was:

```
./micromamba shell init -s bash -p ~/micromamba
export MAMBA_ROOT_PREFIX=~/micromamba
export MAMBA_EXE=$(pwd)/micromamba
. $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
```

Only then I could create an environment. Was I doing something wrong before? Or are the help commands actually incomplete?
Thanks!

**Comment by dhirschfeld** [comment]
Just curious here but after "initializing" your shell did a *new* shell then work?

At least with conda, (on Windows) I'm pretty sure initializing only affects new shells.

**Comment by wolfv** [comment]
yes, when you do shell init, your `~/.zshrc` file should be modified. You then need to either `source ~/.zshrc` or start a new shell to have the variables (including MAMBA_ROOT_PREFIX) set.

**Comment by marimeireles** [comment]
I sourced it, and it didn't work for me, I had to follow these ^

**Comment by marimeireles** [comment]
It works for me when I'm near @wolfv
