### ISSUE TITLE
Remove oversized banner 

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/mamba#66]
Some people apparently don't smirk every time they see the **awesome** banner :)

So we'll get rid of it for something more grown-up-looking.

**Comment by SylvainCorlay** [comment]
No, I think we need the tail of the snake to be longer, and continue on the side of the mamba logs, and cross the screen another time in the end around another tree branch.

**Comment by analog-cbarber** [comment]
The banner is cool, but I wish I could turn it off without having to resort to full quiet mode.

**Comment by aldanor** [comment]
Is there a way to silence the banner for good? Banner being nice and all, it's hurting UX in cases where you have a small terminal window and every single command scrolls the buffer up by 23 lines just to show the banner first.

**Comment by SylvainCorlay** [comment]
> silence the banner for good

Nooooo! ;)

**Comment by SylvainCorlay** [comment]
Yes, I assume we could have a `--no-banner` option. But I think the banner does add a "fun" part to it.

**Comment by SylvainCorlay** [comment]
@aldanor do you fell like you could contribute a `--no-banner` option?

**Comment by aldanor** [comment]
Yea, I could look into that. Simply adding `--no-banner` wouldn't solve it fully though, since now you'd need to choose between having your buffer scroll by 23 extra lines or typing extra 12 letters on every command. Is there some mamba-specific config file somewhere that it reads so it can be stored there as well - we can leave it undocumented :)

**Comment by analog-cbarber** [comment]
Yes, this does seem like the kind of thing you would want to control in a user config file. Short of that, you could just support a MAMBA_NO_BANNER environment variable.

**Comment by aldanor** [comment]
> Yes, this does seem like the kind of thing you would want to control in a user config file. Short of that, you could just support a MAMBA_NO_BANNER environment variable.

Or `NO_SNAKES_PLEASE=1` 😀

Alright, I'll take a look.

**Comment by jpmvferreira** [comment]
The pull request that was merged doesn't seem to work with micromamba, either with the config file or with the environment variable.

Is it possible to extend this feature to micromamba?

**Comment by wolfv** [comment]
Sure! Do you want to send in a PR?

**Comment by jpmvferreira** [comment]
I wish that I could, but I'm far from being able to understand half of what's going in the source code.

If it's of any use the banner shows up with almost all the subcommands I've tested (`install`, `remove`, `info`, `env list`, `create`, `clean` and `update`) and the help dialog.

Also there seems to be a discussion to disable to banner in `mamba` over at #984, so this post probably shouldn't be here.

Regarding that pull request however, `micromamba` doesn't seem to recognize the `show_banner` option:
```console
$ mb config list
channels:
  - conda-forge
```

Where the file `~/.mambarc` is as follows:
```
show_banner: false

channels:
  - conda-forge
```

And as for setting the environment variable which seems to work for `mamba`, according to #1074, it doesn't seem to work for `micromamba`:
```console
$ MAMBA_NO_BANNER=false micromamba env list

                                                                        __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

  Name   Active  Path                                   
──────────────────────────────────────────────────────────
  base           /home/undercover/.micromamba           
  emcee          /home/undercover/.micromamba/envs/emcee
  sc             /home/undercover/.micromamba/envs/sc  
```

**Comment by corneliusroemer** [comment]
@jpmvferreira I think this PR means no more banner anywhere from 1.4.5 onwards: #2298
